/** @type {{ id: string, title: string, tagline: string, rules: string[], genre: string, controls: string, accent: string, tips?: string }[]} */
const GAMES = [
  {
    id: "avalanche",
    title: "Avalanche",
    tagline: "Dodge icicles with a penguin.",
    rules: [
      "Move your mouse to slide the penguin along the bottom of the screen.",
      "Icicles fall from the sky on random paths and loop when they pass the bottom.",
      "Touch any icicle and the run ends immediately.",
    ],
    genre: "action",
    controls: "Mouse",
    accent: "#5eead4",
  },
  {
    id: "asteroids",
    title: "Asteroids",
    tagline: "Shoot shrinking space rocks.",
    rules: [
      "Grey asteroids spawn at the top and bounce around the play area.",
      "Click in the bottom strip to fire small red shots straight upward.",
      "When a shot hits an asteroid, the rock shrinks and your score rises by 0.25.",
      "The “Radii Passed” counter tracks total asteroid size on the field.",
    ],
    genre: "action",
    controls: "Click (bottom strip)",
    accent: "#a78bfa",
  },
  {
    id: "fruitninja",
    title: "Fruit Ninja",
    tagline: "Slice flying food before time runs out.",
    rules: [
      "Move the mouse over circles and rectangles to “slice” them and earn points.",
      "Food drifts in from the left; missed pieces respawn and keep moving.",
      "Beat the target score before the timer hits zero to advance a level.",
      "Fail to reach the target in time and the game ends.",
    ],
    genre: "action",
    controls: "Mouse (hover)",
    accent: "#f472b6",
  },
  {
    id: "helicopter",
    title: "Helicopter",
    tagline: "Hold to rise, release to fall.",
    rules: [
      "Wait through the countdown, then hold the mouse button to climb and release to drop.",
      "Steer through gaps between green ceiling/floor terrain and floating obstacles.",
      "Score increases while you stay alive.",
      "Hit a wall, obstacle, or the top/bottom edge to lose.",
    ],
    genre: "action",
    controls: "Mouse hold / release",
    accent: "#60a5fa",
  },
  {
    id: "planeshooter",
    title: "Plane Shooter",
    tagline: "Bomb targets from a moving plane.",
    rules: [
      "Move the mouse to fly the plane anywhere on screen.",
      "Click to drop bombs that fall with gravity onto grey blocks scrolling in from the right.",
      "Bomb explosions can chain and destroy nearby enemies.",
      "You have 3 lives—enemy fire or collisions cost a life.",
    ],
    genre: "action",
    controls: "Mouse · click to bomb",
    accent: "#38bdf8",
  },
  {
    id: "mousecatcher",
    title: "Mouse Catcher",
    tagline: "Survive four stages of line attacks.",
    rules: [
      "After the intro prompt, move the red dot with your mouse.",
      "Black line enemies sweep from the edges; touching one costs a life (3 total).",
      "Every 10 seconds you advance a level and more hazards appear.",
      "Reach level 5 without losing all lives to win.",
    ],
    genre: "action",
    controls: "Mouse",
    accent: "#fb7185",
    tips: "Allow browser popups for the intro prompt.",
  },
  {
    id: "dragway",
    title: "Dragway",
    tagline: "Drag, dodge, and collect coins.",
    rules: [
      "Drag your circle anywhere to move; you also drift downward each frame.",
      "Blue blocks fall from the left and right lanes—collision ends the game.",
      "Grab yellow coins for points; higher scores spawn obstacles faster.",
      "Passing score thresholds increases coin value multipliers.",
    ],
    genre: "action",
    controls: "Drag",
    accent: "#fbbf24",
  },
  {
    id: "bubbleblaster",
    title: "Bubble Blaster",
    tagline: "Shoot bubbles that match the target color.",
    rules: [
      "A grid of colored bubbles sits at the top; your next shot color is shown at the bottom.",
      "Click where you want to aim— a bubble fires from the center bottom toward that point.",
      "Matching your shot color to a grid bubble removes both (40 total to clear).",
      "Wrong-color hits or shots into the launcher area waste the bubble.",
    ],
    genre: "puzzle",
    controls: "Click to aim",
    accent: "#34d399",
  },
  {
    id: "crazball",
    title: "CraZ Ball",
    tagline: "Click the right colors on a shrinking ball.",
    rules: [
      "A large circle changes color on a timer; click it when you can.",
      "Green or yellow: +1 score and the ball shrinks.",
      "Red: −1 score and the ball grows.",
      "Missing the ball entirely shrinks score and grows the ball.",
      "Win by shrinking the ball to radius 8; lose at score 0 or if the ball grows huge.",
    ],
    genre: "reflex",
    controls: "Click",
    accent: "#4ade80",
  },
  {
    id: "hitthemole",
    title: "Hit the Mole",
    tagline: "Whack the green mole before time’s up.",
    rules: [
      "Nine holes form a grid; a green “mole” circle jumps to random holes.",
      "Click the green mole for +1 point; clicking a hole without the mole costs 1 point.",
      "You have 90 seconds of active play.",
      "When time expires, walls close in— the board shrinks and clicking stops.",
    ],
    genre: "reflex",
    controls: "Click",
    accent: "#a3e635",
  },
  {
    id: "balloonpop",
    title: "Balloon Pop",
    tagline: "Catch falling snacks.",
    rules: [
      "Orange food falls from the top of the sky-blue screen.",
      "Click the food before it leaves the bottom to score.",
      "If food falls off-screen you lose a life (start with 3).",
      "Every 7 points levels up the fall speed; survive to keep climbing.",
    ],
    genre: "reflex",
    controls: "Click",
    accent: "#f9a8d4",
  },
  {
    id: "cherrypicking",
    title: "Cherry Picking",
    tagline: "Fill the basket before the clock runs out.",
    rules: [
      "Cherries spawn in the grass; click one to send it into the orange basket.",
      "Each successful pick adds a little time back to the clock.",
      "Hit score milestones (20, 40, …) for bigger time bonuses.",
      "The timer ticks down every second— if it reaches 0, game over; keep time above 30 when the round ends to win.",
    ],
    genre: "reflex",
    controls: "Click",
    accent: "#ef4444",
  },
  {
    id: "bughunt",
    title: "Bug Hunt",
    tagline: "Tag the bug, track your accuracy.",
    rules: [
      "A rectangle “dino” marches across the screen continuously.",
      "Click directly on the dino to earn 100 points and respawn it elsewhere.",
      "Every click counts as a try— misses lower your accuracy percentage.",
      "No timer; chase the highest score and accuracy you can.",
    ],
    genre: "reflex",
    controls: "Click",
    accent: "#86efac",
  },
  {
    id: "kickups",
    title: "Kickups",
    tagline: "Keep the ball in the air.",
    rules: [
      "A ball sits at the bottom with gravity pulling it down each frame.",
      "Click the ball to kick it— random horizontal speed and a strong upward boost.",
      "Your score ticks up while the ball is airborne.",
      "Hit the ground or side walls and the ball resets to center with score wiped.",
    ],
    genre: "reflex",
    controls: "Click the ball",
    accent: "#fde047",
  },
  {
    id: "linecross",
    title: "Line Cross",
    tagline: "Feed the goal without hitting the sweeper.",
    rules: [
      "Click to launch a red dot from the bottom toward the height you clicked.",
      "If the dot crosses above the middle line, the grey goal circle grows.",
      "A horizontal line sweeps left and right— hitting a red dot ends the run.",
      "Grow the grey goal to the target size without touching red to win; each success speeds the line up.",
    ],
    genre: "puzzle",
    controls: "Click",
    accent: "#c4b5fd",
  },
  {
    id: "clicktarget",
    title: "Click Target",
    tagline: "Race the countdown to 100 points.",
    rules: [
      "A target number appears in the center; every click lowers it by 1 and raises your score by 1.",
      "When the target hits 0, a new random target (5–30) appears.",
      "A separate timer counts down from 500— beat the clock.",
      "Reach 100+ points before the timer ends to trigger the confetti finish.",
    ],
    genre: "puzzle",
    controls: "Click",
    accent: "#67e8f9",
  },
  {
    id: "reactionclick",
    title: "Reaction Click",
    tagline: "Click green as fast as you can.",
    rules: [
      "A large circle waits on screen; occasionally it flashes green.",
      "Only click while it is green— that locks in your reaction time for the trial.",
      "The circle moves to a new spot after each successful click.",
      "Complete 9 trials; your average is printed in the browser console (F12).",
    ],
    genre: "reflex",
    controls: "Click when green",
    accent: "#fdba74",
    tips: "Open the developer console to see your average after trial 9.",
  },
  {
    id: "lockdownstar",
    title: "Lockdown Star",
    tagline: "Four-level lockdown escape quest.",
    rules: [
      "Level 1: arrow keys move a blue square; visit colored locks, remember PIN prompts, and enter combined codes.",
      "Later levels add shooting (aim with mouse, click to fire), barriers, cannons, missiles, and viruses.",
      "Read every popup carefully— progress is gated on codes and reaching certain map areas.",
      "Health is shown on screen; losing it ends the run.",
    ],
    genre: "adventure",
    controls: "Arrows · mouse · prompts",
    accent: "#e879f9",
    tips: "Allow popups for readLine prompts. Long game— save codes the locks give you.",
  },
];
